pragma Singleton

import QtQuick 2.11

Item {
    readonly property color mainBG: "#BB5B6B63"
    readonly property color closeBtnBG: "#fc625d"
    readonly property color closeBtnText: "#000000"
    readonly property color topBtnBG: "#fdbc40"
    readonly property color topBtnText: "#000000"
    readonly property color startVerText: "#aaaaaa"
    readonly property color startBG: "#eeeeee"
    readonly property color roomIdInpText: "#000000"
    readonly property color roomIdInpTextErr: "#ff0000"
    readonly property color roomIdInpBorder: "#7a5fee"
    readonly property color roomIdBtnBorder: "#7a5fee"
    readonly property color roomIdBtnText: "#ffffff"
    readonly property color roomIdBtnGrad0: "#4d32e1"
    readonly property color roomIdBtnGrad1: "#6914ca"
    readonly property color splitLine: "#aaeeeeee"
    readonly property color infoRoomIdIcon: "#FF93D3"
    readonly property color infoRoomIdText: "#ffffff"
    readonly property color infoOnlineIcon: "#23ade5"
    readonly property color infoOnlineText: "#ffffff"
    readonly property color infoFansIcon: "#fb7299"
    readonly property color infoFansText: "#ffffff"
    readonly property color musicBtnBG: "#35cd4b"
    readonly property color musicBtnText: "#000000"

    readonly property color avatarBG: "#eee"
    readonly property color avatarBorder: "#67EB6D"
    readonly property color danmuTextMain: "#ffffff"
    readonly property color danmuTextUname: "#67EB6D"
    readonly property color danmuTextUtitle: "#FF5F00"

    readonly property color giftUname: "#FFE87A"
    readonly property color giftGname: "#64E8FF"

    readonly property color musicSettingBG: "#77005077"
    readonly property color musicSettingTitle: "#ffffff"
    readonly property color musicListBG: "#77005077"
    readonly property color musicListTitle: "#ffffff"
    readonly property color musicListText: "#ffffff"
    readonly property color musicSinger: "#ffffff"
    readonly property color musicNowPlaying: "#ffffff"
    readonly property color musicProgressBarBG: "#e6e6e6"
    readonly property color musicProgressBarContent: "#0078d7"
    readonly property color musicTips0: "#57EB5C"
    readonly property color musicInfo1: "#57EB5C"
    readonly property color musicInfo1Change: "#ff0000"
    readonly property color musicPlaySym: "#23ade5"
    readonly property color musicPlaySymErr: "#c62f2f"
    readonly property color musicPlaySymWarn: "#ffe300"
    readonly property color musicPlaySymLoading: "#23ade5"
    readonly property color musicVolHandleBG: "#f6f6f6"
    readonly property color musicVolHandleBGPressed: "#f0f0f0"
    readonly property color musicVolHandleBorder: "#bdbebf"
}
